// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQYhP7Ag-1XR_X5nKA7wKpLJ00bztvuCM',
    appId: '1:597811317186:web:38583106ff211fe5ea2e5b',
    messagingSenderId: '597811317186',
    projectId: 'shop-sd',
    authDomain: 'shop-sd.firebaseapp.com',
    storageBucket: 'shop-sd.appspot.com',
    measurementId: 'G-E4HT8MLQEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL3ibCA0JSHCOKYyu2jZ1sqmnzw1_9L8',
    appId: '1:597811317186:android:290350d19c03db0dea2e5b',
    messagingSenderId: '597811317186',
    projectId: 'shop-sd',
    storageBucket: 'shop-sd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0qOOEgEIo9nj581jr-KSFj8TzPB1NBtc',
    appId: '1:597811317186:ios:f4868916227e2519ea2e5b',
    messagingSenderId: '597811317186',
    projectId: 'shop-sd',
    storageBucket: 'shop-sd.appspot.com',
    iosBundleId: 'com.shaza.shopping.sdShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0qOOEgEIo9nj581jr-KSFj8TzPB1NBtc',
    appId: '1:597811317186:ios:af3c3828362b20f1ea2e5b',
    messagingSenderId: '597811317186',
    projectId: 'shop-sd',
    storageBucket: 'shop-sd.appspot.com',
    iosBundleId: 'com.shaza.shopping.sdShop.RunnerTests',
  );
}
